export const URL = {
    Home: "/",
    About: "/about",
    Works: "/works",
    Blog: "/blog",
    Price: "/price",
    Contact: "/contact",
    News: "/news",
    Privacy: "/privacy",
    Estimate: "/estimate",
    Area: "/area",
    AreaTsudanuma: "/area/tsudanuma",
    AreaYachiyo: "/area/yachiyo",
    AreaKamagaya: "/area/kamagaya",
}